import Products from "@/components/Home/Products";
import React from "react";

export const metadata = {
  title: "All Products",
  description: "Generated by create next app",
};
const ProductPage = () => {
  return (
    <div>
      <Products />
    </div>
  );
};

export default ProductPage;
